### ISSUE TITLE
Feedback on week 12 project progress for CS2113T-F14-3

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-F14-3/main#214]
## Team progress for mid-`v1.4`
* Milestones setup:
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
* Milestone `v1.4` properly managed:
   * [x] A suitable deadline set [your deadline: 2019-11-11] (:heavy_check_mark: well done!)
   * [x] Issues allocated to it e.g., https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/136 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/135 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/134 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/133 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/132 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/130 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/129 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/128 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/127 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/126 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/123 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/122 (:heavy_check_mark: well done!)
## Individual progress of @calebtay for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/136 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/123 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/122 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @tyeryan for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/134 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/130 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/129 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/123 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/122 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @tehzihuai for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/135 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/128 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/123 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/122 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @benitokun123 for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/127 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/123 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/122 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @langyanbin0314

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-08 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
