### ISSUE TITLE
Feedback on week 13 project progress for CS2113T-F14-3

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-F14-3/main#239]
## Team progress for `v1.4`
* Milestone `v1.4` properly managed:
   * [x] A suitable deadline set [your deadline: 2019-11-11] (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
* [x] New JAR released on GitHub in the past 2 weeks (:heavy_check_mark: well done!)
## Individual progress of @calebtay for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F14-3/main/issues/136 https://github.com/AY1920S1-CS2113T-F14-3/main/issues/123 https://github.com/AY1920S1-CS2113T-F14-3/main/issues/122 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @tyeryan for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F14-3/main/issues/134 https://github.com/AY1920S1-CS2113T-F14-3/main/issues/130 https://github.com/AY1920S1-CS2113T-F14-3/main/issues/129 https://github.com/AY1920S1-CS2113T-F14-3/main/issues/123 https://github.com/AY1920S1-CS2113T-F14-3/main/issues/122 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @tehzihuai for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F14-3/main/issues/135 https://github.com/AY1920S1-CS2113T-F14-3/main/issues/128 https://github.com/AY1920S1-CS2113T-F14-3/main/issues/123 https://github.com/AY1920S1-CS2113T-F14-3/main/issues/122 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @benitokun123 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F14-3/main/issues/127 https://github.com/AY1920S1-CS2113T-F14-3/main/issues/123 https://github.com/AY1920S1-CS2113T-F14-3/main/issues/122 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @langyanbin0314

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-15 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
