### ISSUE TITLE
Feedback on week 9 project progress for CS2113T-F14-3

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-F14-3/main#64]
## Team progress for `v1.2`
* [ ] Team PR created to the upstream repository with the title `[AY1920S1-CS2113T-F14-3] Contact List Pro`(:exclamation:)
* Milestone `v1.2` properly managed:
   * [ ] A suitable deadline  set(:exclamation:)
   * [x] Issues allocated to it https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/41 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/33 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/31 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/10 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/8 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/6 (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [ ] Milestone explicitly closed(:exclamation:)
   * [ ] Code tagged as `v1.2`(:exclamation:)
* Milestones setup:
   * [x] Milestone `v1.2` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.3` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
* Milestone v1.3 planned:
   * [ ] A suitable deadline  set(:exclamation:)
   * [ ] Issues allocated to it (:exclamation:)
## Individual progress of @calebtay for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/41 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/10 (:heavy_check_mark: well done!)
## Individual progress of @tyeryan for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/31 (:heavy_check_mark: well done!)
## Individual progress of @tehzihuai for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/33 (:heavy_check_mark: well done!)
## Individual progress of @benitokun123 for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/8 (:heavy_check_mark: well done!)

Tutor: @langyanbin0314

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-10-18 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
