### ISSUE TITLE
Feedback on week 10 project progress for CS2113T-F14-3

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-F14-3/main#94]
## Team progress for mid `v1.3`
* Milestone `v1.3` properly managed:
   * [x] A suitable deadline 2019-10-30 set(:heavy_check_mark: well done!)
   * [x] Issues allocated to it e.g., https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/87 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/69 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/68 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/67 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/66 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/65 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/21 (:heavy_check_mark: well done!)
* [x] New JAR released on GitHub.(:exclamation: try to do by next milestone)
* Milestones setup:
   * [x] Milestone `v1.3` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
## Individual progress of @calebtay for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.3` milestone https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/69 https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/68 (:heavy_check_mark: well done!)
## Individual progress of @tyeryan for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.3` milestone (:exclamation: try to do by next milestone)
## Individual progress of @tehzihuai for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.3` milestone (:exclamation: try to do by next milestone)
## Individual progress of @benitokun123 for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.3` milestone https://github.com/AY1920S1-CS2113T-F14-3/RoomShare/issues/87 (:heavy_check_mark: well done!)

Tutor: @langyanbin0314

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-10-25 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
